### ISSUE TITLE
(later) use the trigram extension i.e. fuzzy search for site-wide search

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#118]
i.e. don't do exact site search

look into:
https://docs.djangoproject.com/en/4.2/ref/contrib/postgres/search/#trigram-similarity

**Comment by evanconway** [comment]
@gregsadetsky Finally decided to check this out again, but noticed there's no search bar anywhere on the site. What is being searched and where should search go?

**Comment by gregsadetsky** [comment]
Heya! We hid the search bar for now but yeah - search should search all events in the events table, but also all static pages

Searching through static pages turned out to be a challenge because of the size of the static pages ... it's sort of not super intuitive to break down / solve as a problem, but we do have a strategy. Happy to share over a call maybe or in person?

**Comment by evanconway** [comment]
I'd love to talk about it in person. I'll message you on zulip.

**Comment by gregsadetsky** [comment]
Just reworked search using postgres indexing. It works! Cheers
