### ISSUE TITLE
rework? search? make it faster -- see what's going on. postgres plan on render? or more indexing?

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#154]

**Comment by reyaw** [comment]
If we wanted to index the archive + static content pages we could split the content field up in another table, either by header or by day if we want to limit the search to pages with event info (read: past month archives)

**Comment by gregsadetsky** [comment]
Used your idea of splitting the static content pages + added postgres indexing. It's fast now! Cheers
