### ISSUE TITLE
fix google analytics?

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#173]

**Comment by gregsadetsky** [comment]
I see that the old site had `_gaq.push(['_setAccount', 'UA-132884809-1']);` AND `5QMQ2M8P9R` -- so we need to double check

**Comment by nycnoise** [comment]
still need to figure out the best way to view / parse / compare this stuff in GA4, but clicks should now show up here: 
<img width="1237" alt="Screen Shot 2023-12-08 at 3 12 25 PM" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/b29eba5a-6535-4dfb-90cf-fe2d493ef4d7">
