### ISSUE TITLE
line break issue? (12/7 @ 9pm)

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#177]
<img width="1033" alt="Screen Shot 2023-12-07 at 12 34 02 PM" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/2246246f-7016-45d2-a5e4-748eaab38072">

**Comment by gregsadetsky** [comment]
yeah short version of it is that the markup coming from the editor is super messy:

<img width="622" alt="image" src="https://github.com/gregsadetsky/nycnoise/assets/1017304/438cbb04-8cc5-48f6-b3e3-804fd5a3a5d0">

quick solution for now: I went to the editor and removed all of the `<div>` (and closing `</div>`) and only kept the `<span>...</span>`

we'll find a better way. closing this for now, and updating the issue below with information about this problem

(this is related to issue https://github.com/gregsadetsky/nycnoise/issues/107)

**Comment by gregsadetsky** [comment]
fixed for now (for this event)
