### ISSUE TITLE
TOC issue

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#178]
at first i thought i'd just been inconsistent about heading sizes, but i think there's a teensy glitch w/ the TOCs... the last headings are bold, even if they're the same heading size, & you can't actually click them?

ex: https://nyc-noise.com/church/ & https://nyc-noise.com/greg/

<img width="355" alt="Screen Shot 2023-12-07 at 1 50 52 PM" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/cad68711-bd9b-4ab1-bd18-2ab3d3c6ba3e">
<img width="323" alt="Screen Shot 2023-12-07 at 1 50 41 PM" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/482f43dc-935b-45b2-bd19-0ae32c4752bc">

**Comment by gregsadetsky** [comment]
yeah I saw some issues there too, sorry! something happened during the import or after I'll take a look

**Comment by nycnoise** [comment]
i guess also just wondering how the TOCs *work* & if i can continue to update / add to / use them? i updated https://nyc-noise.com/access/ (w/ some snarky stuff about eric adams) & noticed that when i changed a heading, it wasn't reflected in the TOC...

**Comment by gregsadetsky** [comment]
100% TOCs don't work and are broken unfortunately! they'd need to be fixed, let's chat about this!

**Comment by nycnoise** [comment]
i'm just fixing these manually YAY TY!
