### ISSUE TITLE
venue override rich text (?)

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#179]
seems like venue overrides should be rich text so i can format info correctly without duplicating all venue fields. they're now bold, but that includes venue name / age policy / neighborhood / borough, e.g. ![image](https://github.com/gregsadetsky/nycnoise/assets/135757981/ef52e713-f923-4b93-bfac-7e2d1deb7063)

**Comment by gregsadetsky** [comment]
this has been done!
