### ISSUE TITLE
(low priority) "last month" in django events

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#197]
the "last month" thing doesn't seem to work, but i didn't notice for literally AGES & don't use that sort tool v often; low priority, just making note!

**Comment by gregsadetsky** [comment]
hey, just making sure -- when I click the "last month" on the right in the admin page (of events), it does work for me:

https://nyc-noise.com/admin/core/event/?starttime=last_month

is that the 'last month' you're referring to?

<img width="335" alt="image" src="https://github.com/gregsadetsky/nycnoise/assets/1017304/d35b7c17-5185-43a4-baad-3276e328e262">

**Comment by nycnoise** [comment]
it's working for me now, too; i don't think i hallucinated, but must've been a fluke!!

**Comment by gregsadetsky** [comment]
oh actually I thought about it more, it must have happened in january! I see the bug, I was incorrectly doing the date math to show you month -1 of the year 2024 :-) so anyway yeah you were right! and the bug disappeared in february, obviously...

**Comment by gregsadetsky** [comment]
fixed this in 0802dde63c87d4c7b0dd75ac6df6749d21d1bb5a and did a bunch of other cleanup/improvements around search.

the previous/next month links should now work in all months - january, december, etc. :-)
