### ISSUE TITLE
mobile page fit issue?

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#210]
![image](https://github.com/gregsadetsky/nycnoise/assets/135757981/f479cfe8-08c5-4db8-bb9c-2fe193266338)

just started happening this evening i think!

**Comment by gregsadetsky** [comment]
It's because of this

![image](https://github.com/gregsadetsky/nycnoise/assets/1017304/7b767fc4-37df-490e-be8d-0c9db4889790)

:) 

Remove/fix that long url and you should be good!

**Comment by nycnoise** [comment]
lololol THANKS AGAIN
