### ISSUE TITLE
venue field requests

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#213]
(i tried to do some of this myself, apologies if it was poorly!!)

**new fields** (not for site display)
• "cap" (CharField) –– for "capacity"; would also love to have this visible in **venue overview**
• "hou$e" (CharField) –– ditto for venue overview (& written like this so i remember it stands for "house fees," lol)
• "booking link" (URLField)
• "backline link" (URLField)

**field changes** (displayed on site)
• make accessibility notes rich text (for email links); is this just CharField → TextField ?

**field changes** (back end)
• how much of a bitch would it be to shorten "accessibility emoji" field name to "♿️" to narrow column space?
<img width="830" alt="screenshot  accessibility emoji" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/73c51b74-8b2b-4413-adbe-b2c294f50735">

**Comment by gregsadetsky** [comment]
Ah ha yeah sorry table/model changes are a tad more involved :) but super appreciate the changes!!

We'll look at them together for sure

**Comment by nycnoise** [comment]
YAY SO COMPLETED
