### ISSUE TITLE
Fix link to early pandemic about page?

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#217]
@nycnoise - the broken link is at the very bottom of https://nyc-noise.com/about/

**Comment by nycnoise** [comment]
tyty, fixed!!

**Comment by gregsadetsky** [comment]
and probably at the the bottom of https://nyc-noise.com/about-2020-05/

the link should go to https://nyc-noise.com/about-2020-03/ ?

**Comment by nycnoise** [comment]
good f*ckin eye pal ty, fixed!
