### ISSUE TITLE
Anchor links to dates don't bring to the exactly right position

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#222]
Repro: go to month of feb, then click a date in march. On mobile (and desktop too), the exact y scroll position that the browser ends up is not the beginning of the day ... but somewhere?

Does this have to do with the sticky header? I.e. the top of the day actually aligns with the top of the page, but because of the sticky header, that portion of the day is hidden?

**Comment by gregsadetsky** [comment]
discussed here -- https://stackoverflow.com/questions/7717894/sticky-header-internal-links -- check solutions

**Comment by nycnoise** [comment]
i noticed this too & ahhh did you already fix it what??!!! :')

**Comment by gregsadetsky** [comment]
I did not fix it yet, no

**Comment by gregsadetsky** [comment]
fixed in d16815e4a1e292048a493ca377f13e89c8fecc4f !
