### ISSUE TITLE
add "future" filter?

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#224]
(okay i know i haven't responded to the display change proposal yet, but read this as conceding the point /  value, lol...)

the Nature of The Thing means that there are way more past events than future events, & if i want to see anything following "next month" i need to go to "all" & scroll through them, which will only get crazier over time... so maybe this month, next month, last month, all, & *future*  (last) ??

**Comment by gregsadetsky** [comment]
ah yeah for sure, a future one makes sense. just added it in abc64200832b856ad929c313119250308818027d -- it's deploying now. (I'll close this once it's live)

actually... try it out, maybe "future" could become the default option? instead of showing you the current month? your call, obviously!

**Comment by nycnoise** [comment]
okay so i've thought about it & YES PLZ, to future as default!!!!

(...but if future is default can we also have a "this month"? cuz i regularly make batch changes to a month's listings...)

**Comment by gregsadetsky** [comment]
of course! just made 'future' the default, and left 'this month' as an option. pushed, will be live soon
