### ISSUE TITLE
Make sure that sitemap includes past (and future) months from db

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#225]
I.e. 2023-12 and further months that are not static pages, but actually populated from db

**Comment by gregsadetsky** [comment]
just confirmed they don't i.e. 2023-12 is not in there, 2024-01 isn't there either etc.

group all events by yyyy/mm (truncdate?) and add those urls to sitemap?

**Comment by nycnoise** [comment]
this is one of the things i've been trying to figure out / thinking thru with archive... that would rule!!!

**Comment by gregsadetsky** [comment]
sorry what do you mean? the sitemap is just [this page](https://nyc-noise.com/sitemap.xml) which is really only picked up by google/bots. were you thinking of something else?

**Comment by nycnoise** [comment]
i was thinking that if this happens for the sitemap, it would also work for the "[past](https://nyc-noise.com/past/)" pages... is that... maybe?

**Comment by gregsadetsky** [comment]
Yeah no good point - the "past" page was imported as a static page and isn't dynamic. It's only changed if you edited it.

The past page is complicated because it includes links to months before we transitioned the site - and those page-months (sorry this is confusing) are also static pages...

Let's talk about it more. But tldr - that past page you linked to is not being kept up to date by django. You should be able to edit it though in the admin as a static page
