### ISSUE TITLE
make a "closed" venue field

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#228]
...or some equivalent for venues we don't want to show up in submission form lists, back end, etc. (many rn under "z__" to push to bottom cuz me lol)

(@pfeyz thought!)

**Comment by gregsadetsky** [comment]
Yep 100000% correct! And then I can funnel them to venues.rip etc ha.

**Comment by nycnoise** [comment]
ACTUALLY YES THO F'REAL????????!!!!!!!!!!!

**Comment by gregsadetsky** [comment]
done in #230! deploying now

also -> bulk admin actions!!

<img width="330" alt="image" src="https://github.com/gregsadetsky/nycnoise/assets/1017304/f5ca0251-fa4b-4a65-8e62-eb5e4e44363c">
