### ISSUE TITLE
"delete venue" in events?

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#233]
just wanted to check, does the red x "delete venue" field, on each "add event" page, actually delete a given venue listing, or does it just remove it from that particular page?

if it deletes the venue listing entirely, can that be removed from "add event" page? (don't want to accidentally remove a venue from a slew of listings...)

**Comment by gregsadetsky** [comment]
That button would normally delete the venue. And yeah that would be not good

So yeah let's remove that button from there

**Comment by gregsadetsky** [comment]
(note for self) https://stackoverflow.com/a/56944902 i.e. the key is to override has_delete_permission

**Comment by gregsadetsky** [comment]
done!
