### ISSUE TITLE
submission form thoughts!!

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#239]
first, BEAUTIFUL YAYYYYYY HURRAYYYY !!!!!!!!! :''''''')
also TRULY OBSESSED with date & time in one line *swoon*

**→ MAYBE BIGGER Qs**

• i _was_ gonna ask if i can still [also] have **submissions sent via email** –– partly to get an alert & know when there's something to approve, but also cuz people often include info & notes & stuff that i'd delete from a listing but still would wanna have a Record of –– but actually... maybe fuck it??? maybe if i find that's happening a LOT with notes etc. i can throw stuff in slush somewhere... ??? i guess lemme know how difficult / complicated email would be, if it's at all a problem this might just be a Moment for Growth :')

• **"closed" vs. "open"**: i've only marked 1 venue "closed" so far, cuz idk if this makes any difference: would it make more sense to set "open" as the default, & then mark things if they're *not* open (i.e., closed)? the way it's set now, **most venues have a red X** to indicate that they are not-closed, & the lone closed spot has a green check... this is how canceled events work, too, but it's over to the far right so i don't see it often lol –– for events being approved, pages being visible, etc. usually green check means it's there & red x means it's not..? just to help my brain not get mixed up

**→ QUICK PRIORITY**

- [x] **add email line**; i wanna know who/where submissions are coming from (& i sometimes follow up with Qs & stuff)

- [x] **lowercase text plz!!** (other order/wording preferences below, lower-priority)

- [x] **add extra copy to bottom**:
"**note:** if there's really **no link** to yr event, plz **email a flyer** to [contact@nyc-noise.com](mailto:contact@nyc-noise.com) w/ subject line "[DATE] FLYER" (e.g. "2/14/24 FLYER") & i'll link to that instead; ty!"

**→ STYLISTIC / ORDER REQUESTS**

sorry heh, you know yr girl has _opinions..._ also apologies that i haven't been practicing updating site stuff on my own, cuz it would def make more sense for me to just fuck around with this stuff a bunch first, but... i think this is what i want!!

below with smaller size text in lines for 1) title, 2) venue override & copy beneath venue override field (can also just have an asterisk & add venue override note to the bottom), 3) ticket link, 4) extra info

––––––––––––––––––––
––––– CURRENT –––––

**Submit Event**

**Start time**: [ ]
Main Link: [ ]
Ticket Link: [ ]
**Title:** [ ]
**Artists:** [ ]
**Venue:** [ ]
Venue Name (if not in list above): [ ]
Description: [ ]
Price: [ ]

––––– PREF –––––

**submit event**

**yr email:** [ ]
**date + time:** [ ]
**link:** [ ]
_(optional)_ **title** / "x presents" or series: [ ]
**artists:** [ ]
**venue:** [ ]
_(if missing)_ **venue:** [ ]
[below that field] _plz include 1) address (or contact email if private), 2) age policy, & 3) wheelchair access basics for entry & restrooms_
**price:** [ ]
_(if different than main link)_ **ticket link:** [ ]
**extra info** _(prolly won't include unless it's related to fundraiser or something, but GO WILD)_**:** [ ]

––––––––––––––––––––
––––––––––––––––––––

**→ FOR ME**

–– thing to figure out = **PRICE**; i don't need single $ sign for default, & i doubt most ppl even know the price cut-offs for $$ (30) + $$$ (50)... will think about it, not urgent, for now i can just change the "$" back to "-----" before approving

**Comment by gregsadetsky** [comment]
> • i _was_ gonna ask if i can still [also] have **submissions sent via email** –– partly to get an alert & know when there's something to approve, but also cuz people often include info & notes & stuff that i'd delete from a listing but still would wanna have a Record of –– but actually... maybe fuck it??? maybe if i find that's happening a LOT with notes etc. i can throw stuff in slush somewhere... ??? i guess lemme know how difficult / complicated email would be, if it's at all a problem this might just be a Moment for Growth :')

so, getting events by email and automatically "importing" them into the admin is not super super easy, but it's something we could tackle in the future.

you can definitely, of course, still say "please submit your events using the new form or by emailing me", obviously, that's perfectly ok.

but automatic email to database is a bit hard-ish.

> • **"closed" vs. "open"**: i've only marked 1 venue "closed" so far, cuz idk if this makes any difference: would it make more sense to set "open" as the default, & then mark things if they're _not_ open (i.e., closed)? the way it's set now, **most venues have a red X** to indicate that they are not-closed, & the lone closed spot has a green check... this is how canceled events work, too, but it's over to the far right so i don't see it often lol –– for events being approved, pages being visible, etc. usually green check means it's there & red x means it's not..? just to help my brain not get mixed up

yeah, good observation and something I had in mind. let's flip it to track whether the venue is open yeah. I'll open an issue.

> **→ QUICK PRIORITY**
> 
> * [ ]  **add email line**; i wanna know who/where submissions are coming from (& i sometimes follow up with Qs & stuff)
> * [ ]  **lowercase text plz!!** (other order/wording preferences below, lower-priority)
> * [ ]  **add extra copy to bottom**:
>   "**note:** if there's really **no link** to yr event, plz **email a flyer** to [contact@nyc-noise.com](mailto:contact@nyc-noise.com) w/ subject line "[DATE] FLYER" (e.g. "2/14/24 FLYER") & i'll link to that instead; ty!"
> 
> **→ STYLISTIC / ORDER REQUESTS**
> 
> sorry heh, you know yr girl has _opinions..._ also apologies that i haven't been practicing updating site stuff on my own, cuz it would def make more sense for me to just fuck around with this stuff a bunch first, but... i think this is what i want!!
> 
> below with smaller size text in lines for 1) title, 2) venue override & copy beneath venue override field (can also just have an asterisk & add venue override note to the bottom), 3) ticket link, 4) extra info
> 
> –––––––––––––––––––– ––––– CURRENT –––––
> 
> **Submit Event**
> 
> **Start time**: [ ] Main Link: [ ] Ticket Link: [ ] **Title:** [ ] **Artists:** [ ] **Venue:** [ ] Venue Name (if not in list above): [ ] Description: [ ] Price: [ ]
> 
> ––––– PREF –––––
> 
> **submit event**
> 
> **yr email:** [ ] **date + time:** [ ] **link:** [ ] _(optional)_ **title** / "x presents" or series: [ ] **artists:** [ ] **venue:** [ ] _(if missing)_ **venue:** [ ] [below that field] _plz include 1) address (or contact email if private), 2) age policy, & 3) wheelchair access basics for entry & restrooms_ **price:** [ ] _(if different than main link)_ **ticket link:** [ ] **extra info** _(prolly won't include unless it's related to fundraiser or something, but GO WILD)_**:** [ ]
> 
> –––––––––––––––––––– ––––––––––––––––––––
> 
> **→ FOR ME**
> 
> –– thing to figure out = **PRICE**; i don't need single $ sign for default, & i doubt most ppl even know the price cut-offs for $$ (30) + $$$ (50)... will think about it, not urgent, for now i can just change the "$" back to "-----" before approving

**Comment by pfeyz** [comment]
> i was gonna ask if i can still [also] have submissions sent via email 

@nycnoise I initially read this as "can I get an alert emailed to me when somebody submits an event". did you mean that or "I want somebody to be able to send an email and it will get imported into the site db automatically."

the latter is definitely more annoying to do, but I think the former would be pretty useful and an extra "notes" field could capture extra notes from users they don't want to be public facing.

**Comment by nycnoise** [comment]
@pfeyz i meant former, but slightly more –– like "can i literally have the submission emailed to me when it is made, which email would serve as an alert (cuz time) but also exist as a record of exactly how the event was submitted"

**Comment by gregsadetsky** [comment]
Yeah that's low lift for sure to email you on submission. Opening an issue

**Comment by nycnoise** [comment]
y'all rule yay
