### ISSUE TITLE
dump/ideas/notes from j

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#24]
i'll close my other issues & just start adding stuff here...

• **EVENT** fields: date, time, [x presents], artists, event & tix links, age/access override, tiny extra text, doors
• **VENUE** fields: address, ages, access link, join/support link, access note, map link

FEATURE BRAINSTORMING:
• easy/intuitive **font size adjustment**
• ability to **"uncheck" ticketmaster & AEG** venues, à la [cambridgeshows.org](url)
• **artist links** (e.g. bandcamp) are a request; is there a way to add this info in tiny or expandable text without it being too busy / messy? if artist links *are* permitted / solicited, consider not allowing instagram? (i worry if it's an option people will *only* submit handles rather than artist names, & i'm really not tryina be a meta-funnel...)
• **calendar integration** w/ gcal, ical 
• **personal show-metrics**: ability to star events of interest, or mark those attended?
• NEW / GOOD: geng brought up some kinda "**remind me**" option to get a text or email x hours prior to the show (sounds easier to implement?)
• **trains:** ability to see closest subway station(s)? could this be another toggle on/off thing?

• **ticketing** ... ??

**Comment by gregsadetsky** [comment]
moved these tasks to issues and long term plan! done for now! but not done! but done!
