### ISSUE TITLE
table of contents flub

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#304]
[apologies for prolly v dumb!!]

there is *1* entry in the [sites like this](http://nyc-noise.com/sites-like-this/) table of contents that won't work... mind letting me know what i did here?

![Screen Shot 2024-07-21 at 2 14 24 PM](https://github.com/user-attachments/assets/d7e65548-492d-4fa0-a2b1-6be751961b07)
![Screen Shot 2024-07-21 at 2 14 44 PM](https://github.com/user-attachments/assets/dd2d8fdb-c849-4c91-8d9d-c24d4f5578f4)

**Comment by gregsadetsky** [comment]
the `<a>` is ok, but in the table itself you have:

<img width="151" alt="image" src="https://github.com/user-attachments/assets/926a0f88-6ad8-4bd0-9659-9a33268f3299">

you have to remove the hashtag from the `id` property :-) make it `usa_mo_stl`, not `#usa_mo_stl`

**Comment by nycnoise** [comment]
omg i forgot to thank you for this, THANK YOU THANK YOU!!! my brain was busted that day idk
