### ISSUE TITLE
create "day of" message that can be optionally included

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#42]
for example, on https://nyc-noise.com/2023-07/#d16, Jessica added a specific day-of message that gets included after the date and before the list of events for that day

create a model to store the date + day-of-message
include the message in the template if it exists

bonus: write a test that adds a message for a specific date and checks that it appears on that date

**Comment by VidyaYadavv1519** [comment]
Hii, Is this issue still available ??
Can you assign me this issue ??

**Comment by gregsadetsky** [comment]
Hey @VidyaYadavv1519 thank you for your interest!

@andrea749 assigned this issue to herself and is working on it right now, so I'd suggest looking at some of the other open issues if that's ok?

Thanks again!
