### ISSUE TITLE
think / implement way of bringing prod data to dev machines

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#59]
- maybe management command?
- should we expose an api on prod that we'll read? do we want to have an api key?
- expose all events and venues via api and go from there..? support cost of maintaining api "just" for this prod->dev data wrangling?
- discuss!

**Comment by gregsadetsky** [comment]
some more thoughts about this:
- make route such as /api/admin/db.json
- let that be the equivalent of 'dumpdata' for event + venue models (and datemessage) -- maybe accept model names as get args..?
- api view should be protected with superuser access -- i.e. user should be logged in and be superuser

flow for user wanting to bring data:
- start management command ("import_data_from_prod") with optional list of tables? event+venue+datemessage..?
- management command opens /admin/...?? view which shows current session cookie id
- user copies this value into the terminal (management command prompt) waiting to receive this value
- management command does request to /api/admin/db.json, passing session id cookie i.e. auth'ing as user
- once db is downloaded, confirmation prompt to delete all local data & replace with downloaded tables

**Comment by reyaw** [comment]
Lots of demand for this one! (Per Django adventures meeting 11/9)

**Comment by gregsadetsky** [comment]
it has been [DONE-Z'O'ed](https://recurse.zulipchat.com/#narrow/stream/407317-django/topic/bring.20prod.20data.20to.20dev!!!!!!!.20it.20work!!!!!!!/near/401453279)!!!!!!  lmk!!!!!!!
