### ISSUE TITLE
import images from current site / static pages

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#80]
related re #69, port over images from current site

this might be easier to do... with a s3 bucket. otherwise, imported files would have to be "imported" by adding them to the repo...? and deploying them every time? really not great.

also.... what happens when you try to add an image via the tinymce rich text editor...?? where does the image go? :-) I'll open a separate issue for that...!

**Comment by pfeyz** [comment]
I'm extracting and downloading all the image files referenced from the wordpress xml dump. The archived wordpress pages reference the old paths like `https://nyc-noise.com/wp-content/uploads/2023/08/flyers.png`. 

@gregsadetsky I haven't looked that closely at how the archived wordpress pages are handled, are they django template files or just text? do you have feelings about setting up 301 redirects for the old image urls vs just rewriting them in the archived pages? or maybe both.

**Comment by gregsadetsky** [comment]
heya! the import "mega" script lives here -- https://github.com/gregsadetsky/nycnoise/blob/4db6f12fa02d9ee51694bdf79e1c8d6ef0d31eba/core/management/commands/import_wordpress_pages.py -- I will re-review this PR and merge it, I think it can/should live in the repo

so yeah, `import_wordpress_pages` parses the XML and does whatever it needs to

I'd suggest that we rewrite URLs then & there i.e. nyc-noise.com/wp-contents/uploads becomes /static/imported-content ....... or rather.......... it should point to the S3 bucket where we will host these assets --- as we don't want to make all of those images part of the repo itself (i.e. we don't want the images to be bundle with django - we just want them in a public S3 bucket)

SO, steps:
- [ ] download all images from the server (via sftp)
- [ ] send them over / wetransfer, and I'll put them up in s3
- [ ] I'll merge the wordpress import PR to bring the code under the main/dev folds
- [ ] you can modify that script to rewrite the image inclusions and point to the S3 bucket
- [ ] would you also be able to take a cursory look through ... all? `<img>` inclusions to make sure that (local) images are only coming from /wp-content/uploads....? like... that we're not forgetting anything..? and also that all images are included via `<img>` tags and no weird wordpress `[img:...url...]` tags or anything?

lmk what you think!

**Comment by gregsadetsky** [comment]
#69 merged! it's all in dev + main now

**Comment by pfeyz** [comment]
yeah that all sounds good to me, and I was thinking the same thing- checking the image urls in the archived pages.
