### ISSUE TITLE
PUNCHLIST -- as of nov 6 2023

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#98]
"what's missing" / next steps? (to launch!)

- [x] links from calendar - thanks @reyaw !!
- [x] go to top links - thanks @SwantjeM !!
- [X] pre-calendar & post-calendar blocks - thanks @SwantjeM !!
- [X] ~stripe subscription link~ (for now j just added in pre-calendar) -- that's good!! let's do that!
- [X] email subscription box -- did a minimal version
- [X] search -- did a minimal version! see [this](https://nycnoise.onrender.com/?s=property)
- [x] menu similar to the current one
  - [x] as mentioned on the call (Nov 30) ->> a model that tracks human label (text) + a URL (just a url field, nothing fancy)
  - [x] THEN add the frontend --> for desktop and mobile, using html and css
  - [x] then......... add a position field/column? and an admin DIY tool to change the menu item positions....?? that's the hard part (and could be not tackled immediately)
- [x] change venue import to import the 'the' as a boolean
  - [x] by default, insert the 'the' -- check that the event template html uses that
- [x] ability to duplicate an event (as a top right button? as a save button but not using save_as since that would remove "save and add another"..?) – j checked off cuz you did it!!
- [x] ordering within same day/hour! see https://github.com/gregsadetsky/nycnoise/issues/101

**Comment by nycnoise** [comment]
• **bullets** before entries! :D (THANK YOUUUUUUU)

**Comment by SwantjeM** [comment]
I just opened a PR for "go to top links" so that can be ticked off when it's merged.

**Comment by gregsadetsky** [comment]
> I just opened a PR for "go to top links" so that can be ticked off when it's merged.

DONE!!

> Also, does "bullets before entries" just mean that we want the event entries listed with a bullet point in front of each of them? if so, I've changed the index.html to display event entries as an unordered list. I'll make another small PR for it, let me know if that is not what we're trying to do.

yes! perfect!! thank you :-) MERGED! DEPLOYED!
